apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker-service
  template:
    metadata:
      labels:
        app: worker-service
    spec:
      containers:
      - name: worker-service
        image: 577327406267.dkr.ecr.us-east-1.amazonaws.com/worker-service:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: worker-service
spec:
  selector:
    app: worker-service
  ports:
  - port: 80
    targetPort: 5000
  type: ClusterIP